project:
  type: website
  output-dir: docs

website:
  title: "Sydney Informatics Hub GPU Cluster Onboarding Guide"
  site-url: https://sydney-informatics-hub.github.io/
  navbar:
    logo: fig/usyd-logo.png
  sidebar:
    style: "docked"
    background: white
    search: true
    contents:
      - href: index.qmd
        text: Home
      - section: "Getting Started with the SIH GPU Cluster"
        contents:
        - text: "Introduction to the SIH GPU Cluster"
          href: notebooks/cluster_intro.html
        - text: "Accessing the SIH GPU Cluster"
          href: notebooks/access.html
      - section: "Getting Started with Run:ai"
        contents:
        - text: "Login"
          href: notebooks/login.html
        - text: "Navigating the User Interface"
          href: notebooks/user_interface.html
      - section: "Run:ai Features"
        contents:
        - text: "Dashboards"
          href: notebooks/dashboards.html
        - text: "Projects"
          href: notebooks/projects.html
        - text: "Environments"
          href: notebooks/environments.html
        - text: "Data Sources"
          href: notebooks/data_sources.html

      - section: "Tutorials"
        contents:
        - text: "Creating a Jupyter Lab workload"
          href: notebooks/jupyter_tutorial.html
        - text: "Creating a Marimo Python workload"
          href: notebooks/marimo_tutorial.html
        - text: "How to transfer data to/from the SIH GPU Cluster"
          href: notebooks/data_transfer.html
        - text: "How to run a terminal using the Command Line Interface (CLI)"
          href: notebooks/CLI.html
        - text: "How to self-install R packages"
          href: notebooks/R_tutorial.html
  cookie-consent: 
    type: express
    style: simple
    palette: light
    policy-url: https://www.sydney.edu.au/privacy-statement.html
  google-analytics: "G-TNWWV3HK57"

  page-footer: "All materials copyright Sydney Informatics Hub, University of Sydney"

format:
  html:
   link-external-newwindow: true
   link-external-icon: true # displays an icon next to external links
   toc: true
   css: [lesson.css]
   theme: cosmo
   code-link: true
   code-fold: false
   
